Update opencost endpoint
truefoundry/infra-charts pull request #38
Opened 2023-06-05 10:52 UTC by akashg3627

2023-06-05 10:54 UTC, dunefro requested changes
Let's bump the Chart version and also bump the default image in values.yaml.
Rest LGTM

2023-06-07 06:02 UTC, dunefro requested changes

2023-06-07 06:02 UTC, akashg3627 commented on charts/tfy-agent/Chart.yaml
> +version: 0.1.4-rc.2
ohk

2023-06-07 06:04 UTC, dunefro approved these changes
LGTM

2023-06-07 06:25 UTC, merged